### ISSUE TITLE
"Could not find quality (the quality) in the list of available qualities."

### ISSUE THREAD

**Issue by E-Zuo** [jangxx/twitch-auto-recorder-3000#4]
when I type:
>python main.py --twitch-clientid <clientid\> --twitch-secret <secret\> -s <username\> --update-interval 0

```
[info] 2022-12-15 20:05:08 - Start recording of twitch user <username> with quality 'best'
[error] 2022-12-15 20:05:09 - Could not find quality 'best' in the list of available qualities. Options are:
```

it show this error, and "**Options are:**" next line shows nothing.

I also do <username\>:quality, as quality is "source", but it show:

```
[info] 2022-12-15 20:12:07 - Start recording of twitch user say_ya_ha_ha with quality 'source'
[error] 2022-12-15 20:12:11 - Could not find quality 'source' in the list of available qualities. Options are: audio_only, 1080p60, worst, best)
```

**Comment by jangxx** [comment]
> --update-interval 0

Don't use an update interval of 0, since that is going to absolutely spam the API and you will get your key banned.

> it show this error, and "Options are:" next line shows nothing.

It seems like streamlink can't find the stream, even though the twitch API reports it as being live. I'm not sure how this could happen, so in this case you need to tell me the actual username of the streamer you are trying to record so I can investigate.

>I also do <username>:quality, as quality is "source", but it show:

It literally says in the message that "source" is not an available quality, so I'm not sure what you expect. These names come from streamlink and "best" should be the same as when you select "Source" on the twitch website.

**Comment by E-Zuo** [comment]
Okay, I will using 1 first.
My test user is "say_ya_ha_ha". (it's my channel...)

**Comment by jangxx** [comment]
I feel like you misunderstand what the update interval actually does. The idea of this script is to always have it running on a server or something, to automatically start the recording once a streamer goes live. There is really no reason to check once a second if a streamer is live. Doing it once per minute or once every few minutes is more than enough. And if you don't want to always have the script running in the background, you don't need to set the interval at all, since the script will immediately check for people being live when it's started. So you can just start the stream and then the recorder right afterwards.

**Comment by E-Zuo** [comment]
I set 1 second because I want record full stream, so that's why I set to 1 (before it's 0).
