### ISSUE TITLE
help with setting up

### ISSUE THREAD

**Issue by Liam942** [jangxx/twitch-auto-recorder-3000#8]
I get the error message "Incomplete config, missing key: streamers"
When I try to put a streamers name in the config and run the app I get an error saying the name is not defined. What I am doing wrong?

**Comment by jangxx** [comment]
Can you send your config file? I'm not exactly sure what you're doing wrong, but it seems like you're not following the format of the config file correctly. You can find an example of a config file in the readme: https://github.com/jangxx/twitch-auto-recorder-3000#usage

Instead of the config file, you can also specify the streamers with the `-s` command line argument, by listing each streamer in its own `-s` argument.

**Comment by jangxx** [comment]
I have never seen that error before. Without providing your config file so that I can try to reproduce it (with the twitch credentials removed obviously), I can't help you.

**Comment by jangxx** [comment]
Did you just send the contents of _./services/twitch_service.py_ for some reason?

I think there seems to be a misunderstanding here. This project is not a library that you use in your own code, it's a ready made script that you just need to configure.

Let's say you want to record twitch streamer `example` every time they go online. In that case you would run the script as follows:

```bash
python main.py -s example --twitch-clientid <clientid> --twitch-secret <secret>
```

And that's it. No reason for you to write any code. And if you don't want to specify parameters as command line switches you can write them into a YAML file instead (see README for the format) and then run the script with

```bash
python main.py -C /path/to/your/config.yaml
```
